version: 2
jobs:
  package:
    working_directory: /tmp/Zeus/
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: tar -cvf "./${CIRCLE_SHA1}.tar" ./
      - persist_to_workspace:
          root: /tmp/Zeus
          paths:
            - ./
  deploy_package:
    working_directory: /tmp/Zeus
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: sudo aptitude install ncftp
      - attach_workspace:
          at: /tmp/Zeus
      - run: ncftpput-R -v -u "zeusarchiver@kolechia.heliohost.org" -p "CircleCI" "./${CIRCLE_SHA1}.tar" "/${CIRCLE_SHA1}.tar"
workflows:
  version: 2
  buildtestdeploy:
    jobs:
      - package
      - deploy_package:
          requires:
            - package
